### ISSUE TITLE
Broken build on master

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/libmarpa#104]
build log is [here](https://github.com/jeffreykegler/libmarpa/files/8525300/log.txt)

**Comment by jeffreykegler** [comment]
@dabrahams Fixed (I hope!) as of commit https://github.com/jeffreykegler/libmarpa/commit/70192920fb8bd992c8fdbb7c18f1cc8186cd120e.

**Comment by dabrahams** [comment]
Thanks.  Might I suggest you set up [Actions](https://github.com/jeffreykegler/libmarpa/actions) so GitHub will let you know the next time something like this happens?

**Comment by dabrahams** [comment]
Confirmed the fix worked for me.

**Comment by jeffreykegler** [comment]
I will look at Github Actions.  Per https://github.com/jeffreykegler/libmarpa/issues/104#issuecomment-1104700499, and absent feedback to the contrary, I will close this issue in a couple of days.

**Comment by jeffreykegler** [comment]
Closed as per https://github.com/jeffreykegler/libmarpa/issues/104#issuecomment-1105853036.
