### ISSUE TITLE
You have no release tags for anything after 8.6.2

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/libmarpa#111]

**Comment by jeffreykegler** [comment]
All the releases after 8.6.2 are development releases and will never have release tags.

Perhaps I should change to a version numbering where the number indicates whether the release is official or developmental.  Perl uses even major numbers for official releases, odd for development

@dabrahams: Do you have a suggestion?  The Perl scheme has the advantage that I'm familiar with it, and the disadvantage that, despite my familiarity, I've already scewed up. :-)

**Comment by dabrahams** [comment]
Thanks for explaining; I have no particular suggestions.
