### ISSUE TITLE
marpa_o_ambiguity_metric and marpa_o_high_rank_only

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/libmarpa#112]
The docs don't make it clear whether marpa_o_high_rank_only can affect marpa_o_ambiguity_metric, i.e. whether the ambiguity metric is reporting whether there are multiple parses accessible through the `Marpa_Order`, or whether there are multiple valid parses *at all*.

**Comment by jeffreykegler** [comment]
Fixed in commit https://github.com/jeffreykegler/libmarpa/commit/4d4af8af761aeb37c7fd5e986a63266f4606f820.  Absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/libmarpa/issues/112#issuecomment-1189601414.
