### ISSUE TITLE
marpa_g_symbol_is_start() behavior is counter-intuitive

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/libmarpa#12]
In working #11 @rns noticed that the `marpa_g_symbol_is_start()` behavior is counter-intuitive.  I need to look into this.

**Comment by jeffreykegler** [comment]
@rns -- This is the fix.  It's makes the behavior consistent with the documentation, but since it is not bug-for-bug backward compatible, I bumped the version number in the commit following this fix.  That's a good idea anyway now that we are re-licensing.

I'll wait a bit to see if this looks OK to you, then close it.

**Comment by rns** [comment]
@jeffreykegler -- the test now passes, so this looks OK and can be closed, thanks.
