### ISSUE TITLE
MARPA_LINKAGE seems to break many installations

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/libmarpa#125]
@jddurand I brought the latest Libmarpa into Marpa::R2 developer's version and the MARPA_LINKAGE change seems to break things on a lot of systems.  An example is in [this log](http://www.cpantesters.org/cpan/report/4d69c0bc-79fe-11ed-aba6-9a79f339625c).  Maybe I should back this change out.    Suggestions?

**Comment by jddurand** [comment]
@jeffreykegler this is because the generated sources are missing extern keywords, i.e.:

* marpa.c from Marpa-R2-11.002_000:
```
# 17051 "./marpa.w"
             const int marpa_major_version;
 const int marpa_minor_version;
 const int marpa_micro_version;
...
# 576 "./marpa.w"

 const int marpa_major_version= 11;
 const int marpa_minor_version= 0;
 const int marpa_micro_version= 1;
```
* marpa.c from Marpa-R2-10.000000
```
# 16805 "./marpa.w"
extern const int marpa_major_version;
extern const int marpa_minor_version;
extern const int marpa_micro_version;
...
# 571 "./marpa.w"

const int marpa_major_version= 9;
const int marpa_minor_version= 0;
const int marpa_micro_version= 3;
```

**Comment by jeffreykegler** [comment]
@jddurand The change happens in one of your commits: https://github.com/jeffreykegler/libmarpa/commit/85001583fda9b4f90490ed5e131e1ddee84fa297.

Any suggestions what to do here?  It's tempting to just back the whole thing out, as too high-risk.  You did warn me that the change was experimental.

**Comment by jddurand** [comment]
I made a comment in this commit. This is experimental, sure, though IMHO if you look at a marpa.c generated with a marpa.w that takes into account my comment, and find that the only difference are those "extern" thingy, this ought to work.

Still, this remain experimental, as you said.

**Comment by jeffreykegler** [comment]
I think, regretfully, I will back this commit out.  A CPANtesters release can take weeks or even months to go on obscure systems, making experiments of this kind a real problem.  The cost-benefit ratio just doesn't work for this one.  Sorry.

**Comment by jeffreykegler** [comment]
I did the back-out in commits https://github.com/jeffreykegler/libmarpa/commit/4d4bf0959cfb542b726cb8b3990f9d046e92393f, https://github.com/jeffreykegler/libmarpa/commit/d02ef9090be85fe7668c72e70a24b739fa3940b7, and https://github.com/jeffreykegler/libmarpa/commit/2ee0c21999714901a0d852943110baad65512454.  [Testing](http://matrix.cpantesters.org/?dist=Marpa-R2+11.003_000) looks a lot better.  I will wait a few days, and if the testing continues to look good, schedule this issue for closing.

**Comment by jeffreykegler** [comment]
[Testing](http://matrix.cpantesters.org/?dist=Marpa-R2+11.003_000) looks good.  Absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/libmarpa/issues/125#issuecomment-1358115456.
