### ISSUE TITLE
'respectively' is not always respective

### ISSUE THREAD

**Issue by rns** [jeffreykegler/libmarpa#26]
e.g.

>Function: int marpa_g_symbol_is_terminal ( Marpa_Grammar g, Marpa_Symbol_ID sym_id)
Function: int marpa_g_symbol_is_terminal_set ( Marpa_Grammar g, Marpa_Symbol_ID sym_id, int value)
These methods, __respectively__, _set and query_ the “terminal status” of a symbol.

s/set and query/query and set/

This is also the case for 

>marpa_g_rule_rank(_set)
marpa_g_rule_null_high(_set)
marpa_g_default_rank(_set)
marpa_g_symbol_rank(_set)
marpa_g_symbol_is_valued(_set)

and not the case for

>marpa_r_earley_item_warning_threshold(_set)
marpa_o_high_rank_only(_set)
marpa_v_rule_is_valued(_set)

where setters precede getters

Is it the verb or method order that need to be reversed?

**Comment by jeffreykegler** [comment]
Obviously, my use of "respectively" is sometimes downright disreputable. :-)

I'll make the order consistently set-then-query, on the idea that, since setting is more important than querying, the other choice would be a little round-about.

**Comment by jeffreykegler** [comment]
I think the above-referenced commit takes care of this.  If you have time, please skim it for any new or missed problems.  If none, it can be closed.

**Comment by rns** [comment]
They all look ok now.
