### ISSUE TITLE
No events for marpa_r_start_input()

### ISSUE THREAD

**Issue by rns** [jeffreykegler/libmarpa#3]
The doc says "Events are generated by the `marpa_g_precompute()`, `marpa_r_earleme_complete()`, and `marpa_r_start_input()` methods." (18.1). 

However, the doc for `marpa_g_precompute()` (11.8) and `marpa_r_earleme_complete()` (12.4) specifies their events as follows:

`marpa_g_precompute()`:
```
  MARPA_EVENT_COUNTED_NULLABLE
  MARPA_EVENT_LOOP_RULES
  MARPA_EVENT_NULLING_TERMINAL
```
`marpa_r_earleme_complete()`:
```
  MARPA_EVENT_EARLEY_ITEM_THRESHOLD
  MARPA_EVENT_EXHAUSTED
```  
and the below events clearly belong to the recognizer (and thus `marpa_r_earleme_complete()`) only:
```
  MARPA_EVENT_SYMBOL_COMPLETED
  MARPA_EVENT_SYMBOL_EXPECTED
  MARPA_EVENT_SYMBOL_NULLED
  MARPA_EVENT_SYMBOL_PREDICTED
```
So, there is apparently no event left to be generated by `marpa_r_start_input()`.

**Comment by jeffreykegler** [comment]
marpa_r_start_input() has the effect of "completing" Earley set 0, so many (most?) of the events that marpa_r_earleme_complete can return are returned by marpa_r_start_input().

**Comment by rns** [comment]
Ok. Perhaps a note to that effect in marpa_r_start_input()'s doc (12.4)?

**Comment by jeffreykegler** [comment]
Fixed in the above referenced commit.
