### ISSUE TITLE
nit: marpa_r_earleme_complete() return type

### ISSUE THREAD

**Issue by rns** [jeffreykegler/libmarpa#44]
> Function: _Marpa_Earleme_ marpa_r_earleme_complete (Marpa_Recognizer r)

vs.

> Return value: On success, the _number of events_ generated

Perhaps change `marpa_r_earleme_complete()` return type to `int`?

**Comment by jeffreykegler** [comment]
Sounds good, and good time for it, since we've started a new major version.

**Comment by jeffreykegler** [comment]
Done in the above referenced commit.  Thanks!
