### ISSUE TITLE
nit: update Abbreviations and vocabulary in marpa.w

### ISSUE THREAD

**Issue by rns** [jeffreykegler/libmarpa#53]
Below are the abbreviations I'd like to add; not sure about STRLOC -- could you review them when you have time so that I file a PR to merge them?

AHFA: Aycock-Horspool finite automaton.
AHM: Aycock-Horspool item.

CIL: Constant Integer List, a variable-length list of integers, which uses AVL's as a memory allocation device.
CILAR: CIL ARena.
source: https://groups.google.com/d/msg/marpa-parser/LPmHm_JG0m8/O4R2-jQgn2YJ
IRL: internal rule.

NOOK, nook: any node of a parse tree, a pun on both "node" and "fork".

LBV: Lightweight boolean vector.

LBW: Lightweight boolean vector word.

|ord_|, |Ord_|, |_ord|, |_Ord|, ord, Ord: ordinal of the Earley set. Often used as a prefix or a suffix.

PSI: a container of data per Earley-set, and within that, per Earley item.

UR: Ur-nodes, precursors of and-nodes and or-nodes.

URS: UR stack.

SRCL: source link.

AIMID: a legacy term for AHM ID, preserved for backward compatibility.

STRLOC: trace source link location?

XRL: internal rule.

XSY: external symbol.

**Comment by jeffreykegler** [comment]
Thanks for doing this!  I like a convention where the acronym-active letter is capitalized in the definition, thus: "PSI: Per Set and Item -- a container of data per Earley set and, within that, Earley Item".

STRLOC is adapted from other programming environments -- I don't actually know what the acronym is for.  It's not a Marpa abbreviation, and for debugging, so need not be included.

And probably a typo: "XRL: external rule".

**Comment by rns** [comment]
Great, I'll do a PR with your comments in mind.

**Comment by jeffreykegler** [comment]
Done with #55.
