### ISSUE TITLE
marpa_g_rule_is_proper_separation() doesn't set MARPA_ERR_NOT_A_SEQUENCE

### ISSUE THREAD

**Issue by rns** [jeffreykegler/libmarpa#60]
Can this be useful? E.g. to distinguish 0 returned to mean "not a sequence" and 0 returned to mean "a sequence where the proper separation flag is not set".

**Comment by jeffreykegler** [comment]
I've addressed this in the above-refenced documentation change.  If that looks OK, let's close this issue.
