### ISSUE TITLE
marpa_g_rule_rank*() vs. marpa_g_rule_null_high*() on MARPA_ERR_NO_SUCH_RULE_ID

### ISSUE THREAD

**Issue by rns** [jeffreykegler/libmarpa#61]
`marpa_g_rule_rank*()` return `-2` when `marpa_g_rule_null_high*()` do `-1` -- on invalid rule id's. Just checking if that's by design to avoid calling `marpa_g_error()` for -1 return value to check after `marpa_g_rule_rank*()`?

**Comment by jeffreykegler** [comment]
That's correct.  Because -2 is valid as a rank, `marpa_g_error()` must be called to distinguish success from failure, which is a nuisance.  Having to do this on a -1 soft error as well would be even more annoying, so there are no soft errors.
