### ISSUE TITLE
Internally contradictory doc

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/libmarpa#78]
> An exhausted parse may cause a failure, in which case marpa_r_earleme_complete() returns an error whose error code is MARPA_ERR_PARSE_EXHAUSTED. For a parse to fail at an earleme due to exhaustion, it must be the case that no alternatives were accepted at that earleme. In fact, in the standard input model, a failure due to parse exhaustion occurs if and only if no alternatives were accepted at the current earleme.
> ...
> Return value: On success, the number of events generated. On failure, -2.

MARPA_ERR_PARSE_EXHAUSTED is 7 or something.

**Comment by jeffreykegler** [comment]
I don't see the contradiction.  Perhaps you're thinking it lies in the possibility of confusing the error code with the number of events?  But for most calls, the error code is usually not the value which is returned on failure.  In most cases, to find the error code, one detects failure, and then interrogates the error code with `marpa_g_error()`.  I hope this is responsive.

**Comment by dabrahams** [comment]
An exhausted parse may cause a **failure** in which case it returns an error whose error code is MARPA_ERR_PARSE_EXHAUSTED (i.e. 53).  But then on failure, this function is specified to return -2.

**Comment by jeffreykegler** [comment]
My nomenclature for return values is set up [in this section](http://jeffreykegler.github.io/Marpa-web-site/libmarpa_api/stable/api_one_page.html#Return-values), and the conventions there are essential to understanding the return value descriptions in the body.

I'll revise the `marpa_r_earleme_complete()` description to be clearer to someone who is skimming the API doc.

What happens on parse exhaustion in `marpa_r_earleme_complete()` is

1. `marpa_r_earleme_complete()` returns -2, indicating failure.  It also sets the error code to `MARPA_ERR_PARSE_EXHAUSTED`.  At this point, the error code is internal to Marpa, and not visible to the user.
2. The user, if they care, calls `marpa_g_error()`, which returns `MARPA_ERR_PARSE_EXHAUSTED`, the error code.

So, yes, l describe two distinct return values, but they are the return values of two distinct calls.

I will leave this issue open until I make the doc revision.

**Comment by dabrahams** [comment]
Thanks.  Just FWIW, I read the section you referenced, thoroughly. I'm a specification nerd, and I'd hardly call what I'm doing with the doc “skimming.”  
There's a lot you could do to make it clearer and much smaller at the same time, if you're interested.

**Comment by jeffreykegler** [comment]
Yes, I am interested in comments on improving the doc.  I just reread "17.4.2 Initializing locations in the stack" and the amount of over-explanation and obscurity in that section is just cringy, so I imagine the kind of stuff you are suggesting is out there is in fact out there.

I find things easiest to manage is the suggestions are broken into multiple issues, rather than made in one big issue.  That way I can use the open/close mechanisms to track my work more readily.

**Comment by dabrahams** [comment]
Certainly, I'll submit separate suggestion issues.

FYI, some of the suggestions I have will lead naturally to API changes because of the virtuous feedback loop between documentation and API design; to be clear, I don't have any expectation of API changes being made, but expect to find the awkwardness of some docs a bit glaring until they are.

**Comment by jeffreykegler** [comment]
Re my reference to skimmers, you were not specifically intended.  Indeed, it was evident at that point your reading is not just careful, but in fact an in-depth study and analysis, which is flattering, 

Nor was the term "skimmer" intended as disparaging of those to whom it did refer.  It is not reasonable for me to expect all (or frankly, even most) of the API doc's readers will read it carefully from beginning to end, or necessarily remember every syllable of what they did read.  Only the other hand, however false that assumption may be, I have to make some such assumption or the doc expands forever and becomes unusable for everybody.

One of the people who counts as a "skimmer" at this point is me, to some extent.  Of course I did write the thing, and read the it from beginning to end many times at one point.  But as was obvious in our IRC discussion re earlemes two nights ago, my memory of its contents is vague, and at points just plain wrong.

So my strategy is by default to assume the reader is carefully going through the doc from beginning to end, but at points, when it's easy to do so, to make concessions to the skimmers.  The confusion that saves may be my own.

**Comment by jeffreykegler** [comment]
I believe commit cadf7f0 addresses this issue.  I will close it in a couple of days absent feedback to the contrary.

**Comment by jeffreykegler** [comment]
Closed as fixed by commit cadf7f0.
