### ISSUE TITLE
Suggestion: clearly separate API misuses from recoverable conditions in error codes

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/libmarpa#79]
Many interpreted languages (e.g. Perl, Python) do not separate precondition violations—which reflect a programming error (MARPA_ERR_NO_SUCH_SYMBOL_ID, MARPA_ERR_INVALID_BOOLEAN)—from conditions that can be expected in a correct program (MARPA_ERR_PARSE_EXHAUSTED).  Given libMarpa's role in supporting a Perl front-end it's understandable that Marpa's error codes do not make this distinction, but many other languages do.  It would be most useful for direct clients of libMarpa, and especially for interfacing it with other languages, if the distinction were clear.  The minimal move would be to document the few conditions that do not reasonably represent programming errors.  Ideally there would also be an API to query whether a given error code indicates a programming error.

**Comment by dabrahams** [comment]
Sorry, one more element of this: document preconditions _as_ preconditions of the functions they attend (Sorry, I'm unable to avoid trimming the doc for this method in other ways):

> `Marpa_Rule_ID marpa_g_rule_new(Marpa_Grammar g, Marpa_Symbol_ID lhs_id, Marpa_Symbol_ID *rhs_ids, int length)`
>
> Returns a new rule in `g` with `lhs_id` as its LHS symbol and its RHS symbols in [`rhs_ids`, `rhs_ids+length`), or -2 if a precondition was violated.
> 
> - Precondition: `lhs_id` has not been used in `g` on the LHS of a sequence rule (MARPA_ERR_SEQUENCE_LHS_NOT_UNIQUE)
> - Precondition: No other rule in `g` directly reduces the same sequence of RHS symbols to the same LHS symbol (MARPA_ERR_DUPLICATE_RULE)

In general you can avoid documenting MANY preconditions on every “method” by making a blanket precondition statement: “All `Symbol_ID` arguments are required to be valid in the method's first argument.” (then you say that the valid symbols in a recognizer are those valid in the grammar it was constructed from, etc.) You also describe `marpa_g_symbol_new(g)` as returning a new valid symbol in `g`.

**Comment by dabrahams** [comment]
Maybe nevermind my 2nd comment for now; it's really not the same point as the first one, and perhaps doesn't make its case compellingly.

**Comment by dabrahams** [comment]
Here's a list of conditions that seem to be not-necessarily-programming-errors.  It includes any conditions that would require nontrivial analysis of the grammar by the client (e.g. cycles):

  MARPA_ERR_NONE,
  MARPA_ERR_BOCAGE_ITERATION_EXHAUSTED,
  MARPA_ERR_GRAMMAR_HAS_CYCLE,
  MARPA_ERR_INACCESSIBLE_TOKEN,
  MARPA_ERR_DUPLICATE_RULE,
  MARPA_ERR_DUPLICATE_TOKEN,
  MARPA_ERR_INACCESSIBLE_TOKEN,
  MARPA_ERR_NOT_PRECOMPUTED,
  MARPA_ERR_NO_PARSE,
  MARPA_ERR_NO_RULES,
  MARPA_ERR_NO_START_SYMBOL,
  MARPA_ERR_NO_TOKEN_EXPECTED_HERE,
  MARPA_ERR_PARSE_EXHAUSTED,
  MARPA_ERR_PROGRESS_REPORT_EXHAUSTED,
  MARPA_ERR_START_NOT_LHS,
  MARPA_ERR_TREE_EXHAUSTED,
  MARPA_ERR_UNEXPECTED_TOKEN_ID,
  MARPA_ERR_UNPRODUCTIVE_START,
  MARPA_ERR_RECCE_IS_INCONSISTENT,

Keeping in mind #81, this list may of course not be complete.

**Comment by jeffreykegler** [comment]
I did not change the handling of failures, but I have considerably revised the documentation, adding and clarifying definitions, sharpening the use of vocabulary, and extensively rewriting.  Most of the changes are in the chapter on "Failure" (starting at https://github.com/jeffreykegler/libmarpa/blob/659442cd4f193f2d3879a7fa9abf99eb4788a6a9/work/dev/api.texi#L1104) and the chapter introducing the method descriptions (starting at https://github.com/jeffreykegler/libmarpa/blob/659442cd4f193f2d3879a7fa9abf99eb4788a6a9/work/dev/api.texi#L1338).

Next I will revise the Return Value Summaries for each Libmarpa method, to make sure they are consistent with the changes make in those two chapters.  After that, I believe I will be able to close this issue.

**Comment by jeffreykegler** [comment]
I have taken the rewrite of the API doc as far as `marpa_r_earleme_complete()`.  I probably should add some sentences about strategies for calling `marpa_r_earleme_complete()` for exhaustion-loving, input-driven, exhaustion-hating and exhaustion-sensitive parsing.

**Comment by jeffreykegler** [comment]
Fixes finished (finally!) as of commit 81ed732.  Absent feedback to the contrary, I will close this after a couple of days.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/libmarpa/issues/79#issuecomment-1201714547.
