### ISSUE TITLE
Bad link in documentation 

### ISSUE THREAD

**Issue by whitten** [jeffreykegler/libmarpa#80]
I don’t know where the source text is to supply a valid pull request but

http://jeffreykegler.github.io/Marpa-web-site/libmarpa_api/stable/api_one_page.html

Has a link to a non existent page 

https://docs.google.com/file/d/0B9_mR_M2zOc4Ni1zSW5IYzk3TGc/edit?usp=sharing

**Comment by jeffreykegler** [comment]
Fixes.  Thank you for finding this.  If there is nothing additional after a couple of days, I will close this issue.

**Comment by jeffreykegler** [comment]
@whitten Note that the link you cite is the stable version, which won't reflect the change for a while.  You can see the change in the latest version: http://jeffreykegler.github.io/Marpa-web-site/libmarpa_api/latest/api_one_page.html

**Comment by whitten** [comment]
I’m still trying to wrap my brain aroun how to make a Maria interface to another language. Are there other docs I can read ?

**Comment by jeffreykegler** [comment]
Closed as fixed by https://github.com/jeffreykegler/libmarpa/commit/fbb38044dff93a13b7fd291fcad5964f92bad8d1.
