### ISSUE TITLE
Some error codes undocumented

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/libmarpa#81]
It's not clear where these codes come from or whether some of them represent programming errors—see #79 (IX_NEGATIVE and IX_OOB codes we can guess do represent programming errors of course).  This list may be partial, but I caught a lot of them.

  MARPA_ERR_AHFA_IX_NEGATIVE,
  MARPA_ERR_AHFA_IX_OOB,
  MARPA_ERR_ANDID_NEGATIVE,
  MARPA_ERR_ANDID_NOT_IN_OR,
  MARPA_ERR_ANDIX_NEGATIVE,
  MARPA_ERR_NOT_TRACING_COMPLETION_LINKS,
  MARPA_ERR_NOT_TRACING_LEO_LINKS,
  MARPA_ERR_NOT_TRACING_TOKEN_LINKS,
  MARPA_ERR_NO_AND_NODES,
  MARPA_ERR_NO_OR_NODES,
  MARPA_ERR_NO_TRACE_YIM,
  MARPA_ERR_NO_TRACE_YS,
  MARPA_ERR_NO_TRACE_PIM,
  MARPA_ERR_NO_TRACE_SRCL,
  MARPA_ERR_ORID_NEGATIVE,
  MARPA_ERR_OR_ALREADY_ORDERED,
  MARPA_ERR_PIM_IS_NOT_LIM,
  MARPA_ERR_SOURCE_TYPE_IS_AMBIGUOUS,
  MARPA_ERR_SOURCE_TYPE_IS_COMPLETION,
  MARPA_ERR_SOURCE_TYPE_IS_LEO,
  MARPA_ERR_SOURCE_TYPE_IS_NONE,
  MARPA_ERR_SOURCE_TYPE_IS_TOKEN,
  MARPA_ERR_SOURCE_TYPE_IS_UNKNOWN,

**Comment by jeffreykegler** [comment]
Many (all?) of the above are mentioned [in the "Internal error codes" section](http://jeffreykegler.github.io/Marpa-web-site/libmarpa_api/stable/api_one_page.html#Internal-error-codes).

Where an error code can only be set by routines which are that are for use only by libmarpa developers (and therefore which routines are also usually "undocumented"), I do not attempt to describe them, and I call them "undocumented".  Here "undocumented" means that while I might mention them in the user docs, I make no attempt to describe their meaning.  Only libmarpa developers (which means usually myself) should see these error codes, and they should read the code for their meaning.

**Comment by jeffreykegler** [comment]
@dabrahams I've marked this "about to be closed", for the reason [given above](https://github.com/jeffreykegler/libmarpa/issues/81#issuecomment-1080964551).  Unless there's feedback indicating a reason for further work on this issue, I will close it in a couple of days.
