### ISSUE TITLE
Progress report reset vague

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/libmarpa#83]
It's not clear from the API doc what it means to reset a progress report.

**Comment by jeffreykegler** [comment]
Fixed as of commit https://github.com/jeffreykegler/libmarpa/commit/6b16601544dd399b5a36795e402a2432d25a284e.  Absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by jeffreykegler** [comment]
The last few commits are to the wrong issue.  Sigh.

Closing this issue as per https://github.com/jeffreykegler/libmarpa/issues/83#issuecomment-1184740102.
