### ISSUE TITLE
Significance of earley set id parameter to marpa_b_new unclear

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/libmarpa#84]
Presumably marpa_b_new returns a bocage containing all valid parse trees ending at that earley set (and starting where?), but it's never quite specified.

Note: calling the parameter `earley_set_id` is a missed opportunity to communicate something useful about its meaning.  Not a substitute for fixing this issue, but it could help.

**Comment by jeffreykegler** [comment]
Fixed as of commit https://github.com/jeffreykegler/libmarpa/commit/c484ea432540e6c012925ce770b6ed13e08b2d87.  Absent feed back to the contrary, I will close this issue after a couple of days.

**Comment by jeffreykegler** [comment]
Closed as per https://github.com/jeffreykegler/libmarpa/issues/84#issuecomment-1187945712.
