### ISSUE TITLE
Contradiction in marpa_v_step() return value summary

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/libmarpa#86]
> When the iteration through the steps is finished, marpa_v_step returns MARPA_STEP_INACTIVE. 
>
> Return value: On success, the type of the step to be performed. This will always be a
> non-negative number. On failure, -2. 

MARPA_STEP_INACTIVE is neither a type of step to be performed, nor is it -2.

**Comment by jeffreykegler** [comment]
Commit https://github.com/jeffreykegler/libmarpa/commit/6b03234ebabadcd2ef1d15953abc1806d8fa73de fixes this.  I'm in the process of rewriting the whole doc, and there are other cleanups I will do in the text nearby, but I will leave those until they occur in order.

Absent feedback to the contrary, I will close this issue in a couple of days.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/libmarpa/issues/86#issuecomment-1120407186.
