### ISSUE TITLE
rule cannot be accessed

### ISSUE THREAD

**Issue by rns** [jeffreykegler/libmarpa#9]
In this code -- https://gist.github.com/rns/b5249d4c12b61421a229 -- after a trivial 1-rule grammar S_lhs ::= S_rhs is created, the rule cannot be accessed by its id. What am I doing wrong?

**Comment by jeffreykegler** [comment]
This is my top priority right now.  I've been taking a while, because I've realized that I'd better set up an independent way to test Libmarpa -- one that does not depend on Kollos or Marpa::R2.

**Comment by jeffreykegler** [comment]
The problem was in the test script -- misplaced parens caused the result a comparison (the integer 1) to be assigned to the rule number, instead of the integer 0, which was the rule id actually returned by Libmarpa.  When 1 was used later as a rule ID, it was correctly reported as invalid.

**Comment by rns** [comment]
Mea culpa. Sorry and thanks for explaining.

**Comment by jeffreykegler** [comment]
No problem.  I am grateful for bug reports and regard the occasional false alarm as the inevitable consequence of what is usually a good thing.
