### ISSUE TITLE
Deprecate LHS terminals

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/libmarpa#90]
trivial1.c line 263 reveals that the terminal-ness of a symbol is not set to 0 by dint of it having appeared on the LHS of a rule, *and* that I can set the terminal-ness of that symbol to 1 without error, despite it having appeared on the LHS of a rule.  IMO that is extremely subtle at best.

**Comment by jeffreykegler** [comment]
The solution here may be to move the "LHS terminal" methods to deprecated methods.  @dabrahams What do you think?

My idea at the beginning with Marpa was to adopt the UNIX philosophy and hand all possible powers to the user, leaving it up to them to figure how not to shoot themselves in the foot.  So, for example, UNIX allows you to put control characters in file names.

I *could* efficiently allow LHS terminals, so I did.  In terms of possible uses, I though perhaps "short-circuiting" rules for debugging, etc, might be an application, but I didn't really consider it necessary to think of possible applications, leaving that up to the imaginative user, as per the UNIX philosophy.

Marpa::R2 doesn't allow LHS terminals, and IIRC nobody has ever found a use for them.

**Comment by dabrahams** [comment]
Tight preconditions lead to more understandable and usable APIs.

**Comment by jeffreykegler** [comment]
I read [that last comment](https://github.com/jeffreykegler/libmarpa/issues/90#issuecomment-1085963482) as support for deprecating LHS terminals.  When I work this issue, I wll move the documentation of LHS terminals to the "Deprecated techniques and methods" section.

**Comment by jeffreykegler** [comment]
With commit https://github.com/jeffreykegler/libmarpa/commit/47d15b95f28d7b37992be28a8e3c83c2be10253d, this fix is complete.  Absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/libmarpa/issues/90#issuecomment-1250098248.  Affects issue #124.
