### ISSUE TITLE
marpa_v_step() API doc deficiencies

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/libmarpa#95]
I need to

1. Make clear that, once `marpa_v_step()` returns `MARPA_STEP_INACTIVE`, every call to `marpa_v_step()` will return `MARPA_STEP_INACTIVE`.
3. Also, I need to document exactly what the start_es_id and es_id values are, especially for nulling symbols.

**Comment by jeffreykegler** [comment]
17.10 Step location accessors

This section describes step accessors which are not basic to stack manipulation,
but that provide other Earley set location information about the parse.
A step's location in terms of Earley sets is called its ES location.
Every ES location is the ID of an Earley set.

These step accessors are implemented as macros.
All of these accessors always succeed, but if called when they are
irrelevant they return an unspecified value. In this context, an
“unspecified value” is a value that is either -1 or the ID of a
valid Earley set, but which is otherwise unpredictable.

ES location is only relevant for parse nodes.
A parse node is either a leaf node or a rule node.
The step type for a rule node is MARPA_STEP_RULE.
A leaf node is either a nulled node,
or a token node.
The step type for a nulled node is MARPA_STEP_NULLING_SYMBOL.
The step type for a token node is MARPA_STEP_TOKEN.

Every parse node has both a start ES location
and an end ES location.
The start ES location is the first ES location of
that parse node.

The end ES location of a leaf is the ES location where
the next leaf symbol in the fringe of the current parse would start.
Typically, this is the location where a leaf node actually starts,
but toward the end of a parse, there may not be an actual next leaf node.

The start ES location of a MARPA_RULE_STEP is the start ES location
of its first child node in the current parse tree.
The end ES location of a MARPA_RULE_STEP is the end ES location
of its last child node in the current parse tree.

Macro: Marpa_Earley_Set_ID marpa_v_es_id (Marpa_Value v)

    Return value: If the current step type is MARPA_STEP_RULE, MARPA_STEP_TOKEN, or MARPA_STEP_NULLING_SYMBOL,
the return value is the end ES location of the parse node.
If the current step type is anything else, the return value is an unspecified value. 

Macro: Marpa_Earley_Set_ID marpa_v_rule_start_es_id (Marpa_Value v)

    Return value: If the current step type is MARPA_STEP_RULE, the start ES location of the rule node.
If the current step type is anything else, an unspecified value. 

Macro: Marpa_Earley_Set_ID marpa_v_token_start_es_id (Marpa_Value v)

    Return value: If the current step type is MARPA_STEP_TOKEN or MARPA_STEP_NULLING_SYMBOL,
the start ES location of the leaf node.
If the current step type is anything else, an unspecified value. 

For every parse node of the current parse tree,
the Earley set length (ES length) of the node is the end ES location,
less the start ES location.
The ES length of a nulled node is always 0.

If v is a valuator whose current step type is MARPA_STEP_NULLING_SYMBOL, it is always the case that

  marpa_v_token_start_es_id(v) == marpa_v__es_id(v)

If v is a valuator whose current step type is MARPA_STEP_RULE or MARPA_STEP_TOKEN,
it is always the case that

  marpa_v_token_start_es_id(v) <= marpa_v__es_id(v)

As an example, let Null be a nulling symbol and let Tok be a non-nullable symbol.
Then a possible fringe is

  Null@0-0, Tok@0-1, Null@1-1, Tok@1-2, Null@2-2

where the fringe is ordered from left to right, and the notation Sym@m-n indicates that the symbol
Sym has ES start location m and ES end location n.
Another example is

  Null@0-0, Null@0-0, Tok@0-1, Null@1-1, Null@1-1, Tok@1-2, Null@2-2, Null@2-2

In this second example note that when a nulled leaf immediately follows another
nulled leaf, both leaves has the same start ES location and the same end ES location.
This makes sense, because nulled symbol instances do not advance the current ES location,
but it also implies that the ES locations cannot be used to uniquely identify a parse node.

**Comment by jeffreykegler** [comment]
The [just previous comment](https://github.com/jeffreykegler/libmarpa/issues/95#issuecomment-1094123627) is a draft of a revision of the "Other step accessors" section in the Libmarpa API doc.

**Comment by dabrahams** [comment]
> it also implies that the ES locations cannot be used to uniquely identify a parse node.

That's no surprise; any rule of the form `A ::= B` demonstrates, even with no nulling symbols.  The LHS symbol + ES locations does, however, uniquely identify a parse node.

**Comment by jeffreykegler** [comment]
No, if I understand you correctly.  If you look at the second example, two successive leaf nodes are `Null@0-0` and `Null@0-0`.  Any number of successive nulled leaves will have identical `<name,start_es,end_es>` triples, and therefore cannot uniquely identify those nulled leaves.

**Comment by dabrahams** [comment]
One of us, at least, is not understanding the other correctly.  I'm saying that even if nullable symbols were not possible, it would still be true that ES locations don't uniquely identify a parse node. I think you want to say

> it also implies that the ES locations and LHS symbol cannot be used to uniquely identify a parse node.

**Comment by jeffreykegler** [comment]
OK, it was I who misunderstood.  https://github.com/jeffreykegler/libmarpa/commit/ec679afe463155df01c15ba3630a16fd3c13678e contains the change you just suggested.

**Comment by jeffreykegler** [comment]
Changes to the ES locators revision doc are tracked in https://github.com/jeffreykegler/libmarpa/blob/issue92/es_locators.txt , so when the time comes I should take the revison from that file and not [the comment above](https://github.com/jeffreykegler/libmarpa/issues/95#issuecomment-1094123627).

**Comment by jeffreykegler** [comment]
Fixed as of commit https://github.com/jeffreykegler/libmarpa/commit/9e8f93f41dd0ae2a1e94546d176233031841ddec.  Absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/libmarpa/issues/95#issuecomment-1195945321.
